name: CMake for Ubuntu

on:
  schedule:
    # execute the workflow on the 1st of every month at 02:00
    - cron:  '0 2 1 * *'

env:
  # the directory of the library's source code (and which contains the CMakeLists.txt)
  LAL_DIR: /home/runner/work/linear-arrangement-library/linear-arrangement-library/lal
  # directories of the different builds
  REL_DIR: ${{github.workspace}}/ubuntu-build-release
  DEB_DIR: ${{github.workspace}}/ubuntu-build-debug
  
jobs:
  ubuntu_build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake on Ubuntu
      run: cmake ${{env.LAL_DIR}} -B ${{env.REL_DIR}} -DCMAKE_BUILD_TYPE=Release ;
           cmake ${{env.LAL_DIR}} -B ${{env.DEB_DIR}} -DCMAKE_BUILD_TYPE=Debug

    - name: Build on Ubuntu
      run: cmake --build ${{env.REL_DIR}} --config Release -j4 ;
           cmake --build ${{env.DEB_DIR}} --config Debug -j4
