name: CMake

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]
  
  #schedule:
  #  # execute the workflow every day at 02:00
  #  - cron:  '0 2 * * *'

env:
  # the directory of the library's source code (and which contains the CMakeLists.txt)
  LAL_DIR: /home/runner/work/linear-arrangement-library/linear-arrangement-library/lal
  # directories of the different builds
  RELEASE_DIR: ${{github.workspace}}/build-release
  DEBUG_DIR: ${{github.workspace}}/build-debug

jobs:
  windows_build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure CMake on Windows
      run: cmake -G "MSYS Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ${{env.LAL_DIR}} -B ${{env.RELEASE_DIR}} -DCMAKE_BUILD_TYPE=Release ;
           cmake -G "MSYS Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ${{env.LAL_DIR}} -B ${{env.DEBUG_DIR}} -DCMAKE_BUILD_TYPE=Debug
    
    - name: Build on Windows
      run: cmake --build ${{env.RELEASE_DIR}} --config Release -j4 ;
           cmake --build ${{env.DEBUG_DIR}} --config Debug -j4
    
  ubuntu_build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake on Ubuntu
      run: cmake ${{env.LAL_DIR}} -B ${{env.RELEASE_DIR}} -DCMAKE_BUILD_TYPE=Release ;
           cmake ${{env.LAL_DIR}} -B ${{env.DEBUG_DIR}} -DCMAKE_BUILD_TYPE=Debug

    - name: Build on Ubuntu
      run: cmake --build ${{env.RELEASE_DIR}} --config Release -j4 ;
           cmake --build ${{env.DEBUG_DIR}} --config Debug -j4
